### PR TITLE
Import ExtraMounts to horizon-operator

### PR DESCRIPTION
**Pull request by fmount**
This patch introduces the `extraMounts` feature and the `Propagation` keys to `horizon-operator`. The purpose is to allow third party entities to provide files (via `Secrets`, `ConfigMaps`, regular `PVCs` and so forth) to the `Horizon` related `Pods`.

Fixes: [OSPRH-5644](https://issues.redhat.com/browse/OSPRH-5644)

### CODE REVIEW

**Comment by bshephar** [comment]
Grazie mille @fmount ++ . 

There's a few moving parts here, so it would be good to cover them with our functional tests. I'm happy to merge it and then add the test as a follow up PR though.

**Comment by fmount** [comment]
> Grazie mille @fmount ++ .
> 
> There's a few moving parts here, so it would be good to cover them with our functional tests. I'm happy to merge it and then add the test as a follow up PR though.

Ciao @bshephar, thank you for the quick review. Yes, I think I'm going to have envTests in a follow up (maybe early Q2), so I can take some time to review the current status of the implemented tests and extend the coverage to the required components.

**Comment by fmount** [comment]
@bshephar rebased and re-checked!

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
