### PR TITLE
Unpin openstack-k8s-operators

### PR DESCRIPTION
**Pull request by kajinamit**
We pinned these to the released versions for the dev preview release but we should resume tracking the latest code.

### CODE REVIEW

**Comment by abays** [comment]
> @kajinamit: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/horizon-operator-build-deploy-kuttl 	[a445aac](https://github.com/openstack-k8s-operators/horizon-operator/commit/a445aacafc7cec25c80431cb7c26769fbf715ce4) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_horizon-operator/209/pull-ci-openstack-k8s-operators-horizon-operator-main-horizon-operator-build-deploy-kuttl/1696531795572428800) 	true 	`/test horizon-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=horizon-operator&pr=209). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:kajinamit).

I see this is failing due to certain dependency issues, but I see other dependency problems when I try to build locally (have tested in two separate environments):

```
[1/2] STEP 11/13: RUN if [ ! -f $CACHITO_ENV_FILE ]; then go mod download ; fi
go: github.com/Venafi/vcert/v4@v4.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
Error: building at STEP "RUN if [ ! -f $CACHITO_ENV_FILE ]; then go mod download ; fi": while running runtime: exit status 1
```

**Comment by abays** [comment]
> > @kajinamit: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name 	Commit 	Details 	Required 	Rerun command
> > ci/prow/horizon-operator-build-deploy-kuttl 	[a445aac](https://github.com/openstack-k8s-operators/horizon-operator/commit/a445aacafc7cec25c80431cb7c26769fbf715ce4) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_horizon-operator/209/pull-ci-openstack-k8s-operators-horizon-operator-main-horizon-operator-build-deploy-kuttl/1696531795572428800) 	true 	`/test horizon-operator-build-deploy-kuttl`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=horizon-operator&pr=209). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:kajinamit).
> 
> I see this is failing due to certain dependency issues, but I see other dependency problems when I try to build locally (have tested in two separate environments):
> 
> ```
> [1/2] STEP 11/13: RUN if [ ! -f $CACHITO_ENV_FILE ]; then go mod download ; fi
> go: github.com/Venafi/vcert/v4@v4.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
> Error: building at STEP "RUN if [ ! -f $CACHITO_ENV_FILE ]; then go mod download ; fi": while running runtime: exit status 1
> ```

I see the failure I hit here is happening in CI for a similiar Keystone PR: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_keystone-operator/304/pull-ci-openstack-k8s-operators-keystone-operator-main-keystone-operator-build-deploy-kuttl/1696501551369031680

**Comment by abays** [comment]
> > > @kajinamit: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > > Test name 	Commit 	Details 	Required 	Rerun command
> > > ci/prow/horizon-operator-build-deploy-kuttl 	[a445aac](https://github.com/openstack-k8s-operators/horizon-operator/commit/a445aacafc7cec25c80431cb7c26769fbf715ce4) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_horizon-operator/209/pull-ci-openstack-k8s-operators-horizon-operator-main-horizon-operator-build-deploy-kuttl/1696531795572428800) 	true 	`/test horizon-operator-build-deploy-kuttl`
> > > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=horizon-operator&pr=209). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:kajinamit).
> > 
> > 
> > I see this is failing due to certain dependency issues, but I see other dependency problems when I try to build locally (have tested in two separate environments):
> > ```
> > [1/2] STEP 11/13: RUN if [ ! -f $CACHITO_ENV_FILE ]; then go mod download ; fi
> > go: github.com/Venafi/vcert/v4@v4.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
> > Error: building at STEP "RUN if [ ! -f $CACHITO_ENV_FILE ]; then go mod download ; fi": while running runtime: exit status 1
> > ```
> 
> I see the failure I hit here is happening in CI for a similiar Keystone PR: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_keystone-operator/304/pull-ci-openstack-k8s-operators-keystone-operator-main-keystone-operator-build-deploy-kuttl/1696501551369031680

Ah, looks like @gibizer figured it out in the Nova operator [1].  We should include the same `replace` here and in other "unpin" PRs.

[1] https://github.com/openstack-k8s-operators/nova-operator/blob/f07662231bdb7d4ea77710d192ae1483b03ee417/go.mod#L95-L97

**Comment by kajinamit** [comment]
Thanks @abays for pointing that out ! I thought to spend some time to dig into it today. I've added that workaround and we'll see if that works for this case.

**Comment by gibizer** [comment]
> Ah, looks like @gibizer figured it out in the Nova operator [1]. We should include the same `replace` here and in other "unpin" PRs.
> 
> [1] https://github.com/openstack-k8s-operators/nova-operator/blob/f07662231bdb7d4ea77710d192ae1483b03ee417/go.mod#L95-L97

I tried to notify all of us over slack about this gotcha but I guess that went unnoticed.

**Review by bshephar — APPROVED** [review]

**Pull request merged**
