### PR TITLE
Sync EnvTest version with k8s version

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Comment by gibizer** [comment]
we need https://github.com/openstack-k8s-operators/horizon-operator/pull/288

**Review by stuggi — APPROVED** [review]
/lgtm

**Comment by gibizer** [comment]
/test horizon-operator-build-deploy-kuttl
```
  - lastTransitionTime: "2024-02-19T08:28:33Z"
    message: TLSInput error occured in TLS sources Secret horizon-kuttl-tests/combined-ca-bundle
      not found
    reason: Error
    severity: Warning
    status: "False"
    type: Ready
```

**Pull request merged**
